pipeline {
    agent any
    stages {
        stage('Chekout') {
            steps {
                git url: 'https://github.com/ESTIA-LMS/LMS_backend.git', branch: 'main'
                echo 'Checkout Completed'
            }
        }
        stage('Build') {
            steps {
                sh 'docker build ./ -t back_api'
            }
        }
        stage('Deploy BDD') {
            steps {
                sudo sh "./cicd/run_mssql_container.sh"
            }
        }
        stage('Deploy API') {
            {
                sudo sh "./cicd/run_node_container.sh"
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
    }
}
