pipeline {
    agent any
    stages {
        stage('Chekout') {
            steps {
                git url: 'https://github.com/ESTIA-LMS/LMS_backend.git', branch: 'main'
                echo 'Checkout Completed'
            }
        }
        stage('Prepare docker environement') {
            steps {
                sh 'docker kill $(docker ps -q) || true'
                sh 'docker container prune -f'
                sh 'docker image prune -f'
                sh 'docker network create lms_network || true'
            }
        }
        stage('Build API image') {
            steps {
                sh 'docker build ./ -t back_api'
            }
        }
        stage('Deploy BDD') {
            steps {
                sh 'chmod +x ./cicd/*.sh'
                sh './cicd/run_mssql_container.sh'
            }
        }
        stage('Deploy API') {
            steps {
                sh 'chmod +x ./api/bin/*.sh'
                sh './api/bin/wait-for-it.sh -t 20 mssql:1433 -- nohup sh ./api/bin/start_api.sh'
            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
    }
}
